import type { ExploreItem } from "./types";

export const exploreItems: ExploreItem[] = [
  {
    id: "explore-mattress",
    title: "Budget foam mattress",
    price: 275,
    source: "NestHaul starter picks",
    url: "#",
    checklistItemId: "mattress",
    category: "Sleep",
    condition: "new",
    logistics: "delivery available",
    notes: "A simple first-night anchor item that stays under the starter mattress budget."
  },
  {
    id: "explore-sheets",
    title: "Two-set cotton sheet bundle",
    price: 55,
    source: "NestHaul starter picks",
    url: "#",
    checklistItemId: "sheets",
    category: "Sleep",
    condition: "new",
    logistics: "delivery available",
    notes: "Covers the urgent bedding basics without buying extra decor yet."
  },
  {
    id: "explore-desk",
    title: "Compact writing desk",
    price: 110,
    source: "NestHaul starter picks",
    url: "#",
    checklistItemId: "desk",
    category: "Work",
    condition: "used",
    logistics: "pickup preferred",
    notes: "A small work surface that fits studio and shared apartment layouts."
  },
  {
    id: "explore-work-chair",
    title: "Adjustable task chair",
    price: 95,
    source: "NestHaul starter picks",
    url: "#",
    checklistItemId: "work-chair",
    category: "Work",
    condition: "used",
    logistics: "pickup or local delivery",
    notes: "Useful if remote work starts before the rest of the apartment is finished."
  },
  {
    id: "explore-cookware",
    title: "Starter skillet and saucepan set",
    price: 75,
    source: "NestHaul starter picks",
    url: "#",
    checklistItemId: "cookware-basics",
    category: "Kitchen",
    condition: "new",
    logistics: "delivery available",
    notes: "Covers the core pan and pot need from the researched kitchen starter list."
  },
  {
    id: "explore-dishes",
    title: "Four-place dinnerware set",
    price: 65,
    source: "NestHaul starter picks",
    url: "#",
    checklistItemId: "dishes",
    category: "Kitchen",
    condition: "new",
    logistics: "delivery available",
    notes: "Enough for a first apartment without overbuying a large entertaining set."
  },
  {
    id: "explore-towels",
    title: "Six-piece towel set",
    price: 42,
    source: "NestHaul starter picks",
    url: "#",
    checklistItemId: "bath-towels",
    category: "Bathroom",
    condition: "new",
    logistics: "delivery available",
    notes: "Keeps the first-week bathroom essentials simple and under budget."
  },
  {
    id: "explore-shower",
    title: "Shower curtain, liner, and rings",
    price: 35,
    source: "NestHaul starter picks",
    url: "#",
    checklistItemId: "shower-basics",
    category: "Bathroom",
    condition: "new",
    logistics: "delivery available",
    notes: "A move-in-day bathroom item that is easy to forget."
  },
  {
    id: "explore-cleaning-kit",
    title: "All-purpose cleaning starter kit",
    price: 38,
    source: "NestHaul starter picks",
    url: "#",
    checklistItemId: "cleaning-kit",
    category: "Cleaning",
    condition: "new",
    logistics: "delivery available",
    notes: "Basic supplies for cleaning before unpacking."
  },
  {
    id: "explore-vacuum",
    title: "Lightweight stick vacuum",
    price: 80,
    source: "NestHaul starter picks",
    url: "#",
    checklistItemId: "vacuum",
    category: "Cleaning",
    condition: "used",
    logistics: "pickup",
    notes: "Useful soon after move-in, especially if rugs or pets are involved."
  },
  {
    id: "explore-closet-storage",
    title: "Freestanding garment rack",
    price: 72,
    source: "NestHaul starter picks",
    url: "#",
    checklistItemId: "closet-storage",
    category: "Storage",
    condition: "used",
    logistics: "pickup",
    notes: "Helps when closet space is limited or delayed by unpacking."
  },
  {
    id: "explore-tool-kit",
    title: "Small apartment tool kit",
    price: 32,
    source: "NestHaul starter picks",
    url: "#",
    checklistItemId: "tool-kit",
    category: "Storage",
    condition: "new",
    logistics: "delivery available",
    notes: "Practical for assembling furniture and fixing small setup problems."
  },
  {
    id: "explore-sofa",
    title: "Used loveseat",
    price: 210,
    source: "NestHaul starter picks",
    url: "#",
    checklistItemId: "sofa",
    category: "Living",
    condition: "used",
    logistics: "pickup with elevator check",
    notes: "A reasonable living-room option once urgent basics are handled."
  },
  {
    id: "explore-floor-lamp",
    title: "Simple floor lamp",
    price: 48,
    source: "NestHaul starter picks",
    url: "#",
    checklistItemId: "floor-lamp",
    category: "Living",
    condition: "new",
    logistics: "delivery available",
    notes: "Adds usable light without committing to bigger decor purchases."
  }
];
